interface BlogPostPageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: BlogPostPageProps) {
  const { slug } = await params;
  return {
    title: `${slug.replace(/-/g, " ")} — Fintrest.ai Blog`,
  };
}

export default async function BlogPostPage({ params }: BlogPostPageProps) {
  const { slug } = await params;

  return (
    <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-16">
      <article>
        <h1 className="font-[var(--font-heading)] text-3xl sm:text-4xl font-bold tracking-tight capitalize">
          {slug.replace(/-/g, " ")}
        </h1>
        <p className="mt-4 text-muted-foreground">
          This article will be generated by the AI SEO engine. Content coming
          soon.
        </p>
      </article>
    </div>
  );
}
