using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Fintrest.Api.Models;

/// <summary>
/// LLM-generated narrative thesis for a stock, combining the quant scoring output with
/// editorial context (what the company does, why the setup matters now, risks, trade plan).
///
/// Generated by <c>AthenaThesisService</c> — typically only for top signals per scan
/// (BUY_TODAY + top WATCH) to keep LLM costs bounded. Cached per (scan_run_id, ticker).
/// </summary>
[Table("athena_theses")]
public class AthenaThesis
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    public long? ScanRunId { get; set; }

    public long StockId { get; set; }

    [Required, MaxLength(16)]
    public string Ticker { get; set; } = "";

    /// <summary>Pattern-matched sub-verdict: "Buy the Dip", "Breakout Setup", "Momentum Run", etc.</summary>
    [Required, MaxLength(64)]
    public string Verdict { get; set; } = "";

    /// <summary>Qualitative risk/style tier — no dollar amounts per compliance model.</summary>
    [Required, MaxLength(64)]
    public string Tier { get; set; } = "";

    /// <summary>Multi-paragraph narrative thesis in Athena's editorial voice.</summary>
    [Column(TypeName = "text")]
    public string ThesisMarkdown { get; set; } = "";

    /// <summary>JSON array of short catalyst strings ("AI capex tailwind", "Analyst upgrade Apr 7").</summary>
    [Column(TypeName = "jsonb")]
    public string CatalystsJson { get; set; } = "[]";

    /// <summary>JSON array of short risk strings ("Earnings May 5", "High beta in weak tape").</summary>
    [Column(TypeName = "jsonb")]
    public string RisksJson { get; set; } = "[]";

    /// <summary>JSON object with entry/stop/target + narrative line.</summary>
    [Column(TypeName = "jsonb")]
    public string TradePlanJson { get; set; } = "{}";

    public int InputTokens { get; set; }
    public int OutputTokens { get; set; }

    [MaxLength(64)]
    public string Model { get; set; } = "";

    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
}
