export const metadata = { title: "Disclaimer — Fintrest.ai" };

export default function DisclaimerPage() {
  const lastUpdated = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <article className="max-w-3xl mx-auto px-6 py-16 prose prose-sm">
      <h1 className="font-[var(--font-heading)] text-3xl font-bold mb-2">Disclaimer</h1>
      <p className="text-muted-foreground text-sm">Last updated: {lastUpdated}</p>

      <h2 id="who-we-are" className="mt-8 text-xl font-semibold">1. Who we are</h2>
      <p>
        Fintrest.ai is a stock research and data-analytics platform operated by
        DSYS Inc. (&ldquo;Fintrest,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo;
        or &ldquo;our&rdquo;). We are a technology company, not a financial
        institution. We are <strong>not</strong> a Registered Investment
        Adviser under the Investment Advisers Act of 1940, <strong>not</strong>{" "}
        a broker-dealer registered with the SEC or FINRA, <strong>not</strong>{" "}
        a Commodity Trading Advisor, and <strong>not</strong> a licensed
        financial planner. We do not custody customer funds, do not execute
        trades, and do not manage portfolios.
      </p>

      <h2 className="mt-6 text-xl font-semibold">2. What Fintrest publishes</h2>
      <p>
        Fintrest publishes educational research outputs, including: quantitative
        signals scored 0–100 across a 7-factor model; plain-English theses
        written by the Lens research layer; reference entry, stop, and target
        levels derived from technical structure; sector-level heatmaps;
        historical performance statistics and audit logs; market commentary;
        and catalysts-based feeds (earnings, insider trades, congressional
        filings, ownership changes).
      </p>
      <p>
        All of this content is produced from public market data. It is
        informational and educational. It does not take into account the
        personal financial situation, investment objectives, risk tolerance,
        tax position, or constraints of any individual user.
      </p>

      <h2 className="mt-6 text-xl font-semibold">3. Nothing on this platform is investment advice</h2>
      <p>
        Nothing on Fintrest.ai — including but not limited to signals, scores,
        Lens theses, reference levels, morning digests, alerts, the audit log,
        blog posts, chat responses, emails, SMS messages, and push
        notifications — constitutes:
      </p>
      <p>
        (a) investment advice of any kind; (b) a personal recommendation to
        buy, sell, hold, or refrain from buying any security; (c) a
        solicitation, offer, or inducement to enter into an investment
        advisory, brokerage, or other financial-services relationship; (d) an
        offer to sell or a solicitation to buy any security in any
        jurisdiction; (e) tax, legal, accounting, or financial-planning
        advice.
      </p>
      <p>
        Specifically, the designations &ldquo;BUY TODAY,&rdquo;
        &ldquo;WATCH,&rdquo; &ldquo;AVOID,&rdquo; or any similar signal label
        are research classifications generated by an automated scoring model.
        They are not recommendations to any user to take any action. Users
        must not interpret any signal, score, thesis, or reference level as a
        personal instruction.
      </p>

      <h2 className="mt-6 text-xl font-semibold">4. You are solely responsible for your decisions</h2>
      <p>
        You are solely responsible for any investment, trading, or financial
        decisions you make. Before acting on any information obtained from
        Fintrest.ai, you should: (a) consider your own financial situation,
        objectives, and risk tolerance; (b) conduct your own research; and (c)
        consult a licensed investment professional, tax advisor, and/or
        attorney. Any decision to buy, sell, hold, or abstain from trading any
        security is yours alone.
      </p>

      <h2 className="mt-6 text-xl font-semibold">5. Performance disclosures</h2>
      <p>
        Any historical performance figures shown on Fintrest.ai — including
        but not limited to hit rates, average returns per signal, win rates,
        drawdowns, and Sharpe ratios — are one of two kinds, and will be
        labeled accordingly:
      </p>
      <p>
        <strong>(a) Backtested / hypothetical performance:</strong> results
        generated by running the current scoring engine over historical data.
        These results do not represent actual trading, actual user outcomes,
        or any real money at risk. They do not include slippage, bid-ask
        spread, commissions, taxes, borrow costs, missed fills, or capacity
        constraints. Real-world trading of the same signals would produce
        materially different results.
      </p>
      <p>
        <strong>(b) Live post-launch performance:</strong> actual outcomes of
        signals published by Fintrest since a stated launch date. These do not
        represent any user&apos;s actual account performance, as no user
        trades every signal at the exact entry and exit prices shown.
      </p>
      <p>
        Past performance — backtested or live — does not guarantee future
        results. Market regimes change. Factors that worked in one period may
        fail in the next. You must not assume future returns will resemble
        past returns.
      </p>

      <h2 className="mt-6 text-xl font-semibold">6. Risk of loss</h2>
      <p>
        Trading stocks involves substantial risk of loss, including the total
        loss of your investment. Using leverage, margin, options, or
        derivatives increases the risk materially. Some securities covered by
        Fintrest research are volatile, thinly traded, or subject to high
        spreads; trading them can result in losses larger than a user
        anticipates. Fintrest cannot and does not represent that any signal,
        strategy, or set of signals is suitable for any particular user.
      </p>

      <h2 className="mt-6 text-xl font-semibold">7. No personalization, no fiduciary duty</h2>
      <p>
        Fintrest does not owe you a fiduciary duty. Lens does not know your
        full financial picture, your account size, your tax situation, your
        existing positions outside what you import, your liquidity needs, or
        your constraints. Lens&apos;s responses are produced from public
        market data and the research framework, not from a personalized
        assessment of your circumstances. Personalization features such as
        Lens Personalized (Elite) improve relevance but do not make the
        output personalized investment advice.
      </p>

      <h2 className="mt-6 text-xl font-semibold">8. Forward-looking statements</h2>
      <p>
        Research commentary, theses, reference levels, and Lens responses may
        contain forward-looking statements — expectations, projections,
        targets, or estimates about future events or market conditions.
        Forward-looking statements are inherently uncertain and subject to
        change without notice. Actual outcomes may differ materially and
        often do.
      </p>

      <h2 className="mt-6 text-xl font-semibold">9. Accuracy of data and models</h2>
      <p>
        Fintrest sources data from third-party providers (including but not
        limited to Polygon, Financial Modeling Prep, Finnhub, and exchange
        feeds). While we work to keep data accurate and timely, we do not
        warrant the accuracy, completeness, or timeliness of any data, signal,
        score, thesis, or reference level. Data feeds can be delayed,
        incorrect, or interrupted. Models can fail. Lens can make mistakes.
        You must verify any data point you intend to rely on for a real
        trading decision.
      </p>

      <h2 className="mt-6 text-xl font-semibold">10. Third-party content</h2>
      <p>
        Fintrest may incorporate or link to third-party content (news
        articles, filings, data, research). Such content is the responsibility
        of the third-party provider, and we make no representation about its
        accuracy or reliability. Inclusion or linkage does not imply
        endorsement.
      </p>

      <h2 className="mt-6 text-xl font-semibold">11. Jurisdiction and eligibility</h2>
      <p>
        Fintrest is offered only to users in jurisdictions where doing so is
        lawful. It is not offered where its offering, use, or distribution
        would be prohibited or would subject DSYS Inc. to registration
        requirements it has not satisfied. Users are responsible for ensuring
        their use of the platform complies with laws in their jurisdiction.
        Nothing on the platform is directed to any user in a jurisdiction
        where such direction would be unlawful.
      </p>

      <h2 className="mt-6 text-xl font-semibold">12. Changes to this disclaimer</h2>
      <p>
        We may update this disclaimer at any time. The current version is
        always posted at{" "}
        <a href="https://fintrest.ai/disclaimer">
          https://fintrest.ai/disclaimer
        </a>{" "}
        with its last-updated date. Continued use of the platform after an
        update constitutes acceptance of the updated disclaimer.
      </p>

      <h2 className="mt-6 text-xl font-semibold">13. Contact</h2>
      <p>
        Questions about this disclaimer:{" "}
        <a href="mailto:legal@dsysinc.com">legal@dsysinc.com</a> · DSYS Inc.,
        United States.
      </p>
    </article>
  );
}
