"use client";

import { motion } from "framer-motion";
import { STATS } from "@/lib/constants";

export function Performance() {
  return (
    <section id="performance" className="relative py-24 sm:py-32 overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-navy" />
      <div className="absolute inset-0 bg-grid opacity-30" />
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[300px] rounded-full bg-primary/10 blur-[120px]" />

      <div className="relative z-10 mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.6 }}
          className="text-center max-w-2xl mx-auto mb-10"
        >
          <span className="inline-block text-sm font-semibold text-primary mb-4 tracking-wide uppercase">
            Audit log
          </span>
          <h2 className="font-[var(--font-heading)] text-3xl sm:text-4xl font-bold text-white tracking-tight">
            Every signal,{" "}
            <span className="gradient-text">audited publicly</span>
          </h2>
          <p className="mt-4 text-white/50 text-lg">
            Every signal the engine publishes is logged and its outcome is
            tracked — winners and losers. The numbers below are backtested;
            live performance since launch is shown separately and never
            blended with backtest results.
          </p>
        </motion.div>

        {/* Hypothetical / Backtested inline badge (SEC Rule 206(4)-1) — must be
            presented with equal prominence to the performance claim. */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="mb-6 flex justify-center"
        >
          <div className="inline-flex flex-wrap items-center justify-center gap-2 rounded-full border border-amber-500/40 bg-amber-500/10 px-4 py-2 text-[11px] sm:text-xs font-bold uppercase tracking-[0.18em] text-amber-300">
            <span>Hypothetical</span>
            <span className="text-amber-300/40">·</span>
            <span>Backtested</span>
            <span className="text-amber-300/40">·</span>
            <span>Jan 2024 – Mar 2026</span>
            <span className="text-amber-300/40">·</span>
            <span>Not live trading results</span>
          </div>
        </motion.div>

        {/* Stats grid */}
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-6">
          {STATS.map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1, duration: 0.5 }}
              className="text-center rounded-2xl border border-white/10 bg-white/[0.03] backdrop-blur-sm p-8"
            >
              <p className="font-[var(--font-heading)] text-4xl sm:text-5xl font-extrabold text-white">
                {stat.value}
              </p>
              <p className="mt-2 text-sm text-white/40">{stat.label}</p>
            </motion.div>
          ))}
        </div>

        {/* Disclosure block — equal prominence to the numbers, NOT a footer footnote. */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4, duration: 0.5 }}
          className="mt-8 rounded-2xl border border-white/10 bg-white/[0.03] backdrop-blur-sm p-6 text-left space-y-3 text-sm text-white/55 leading-relaxed max-w-4xl mx-auto"
        >
          <p>
            The numbers above are{" "}
            <span className="text-amber-300 font-semibold">
              hypothetical backtested results
            </span>{" "}
            generated by running the current scoring engine over historical
            data for January 2024 through March 2026. They do not represent
            actual trading, actual user accounts, or actual outcomes any user
            experienced. No user was trading these signals during the backtest
            window.
          </p>
          <p>
            Backtests do not account for real-world frictions, including
            slippage, spread, commissions, taxes, missed fills, borrow costs,
            or capacity constraints. Real-world results from following the
            same signals would be materially different.
          </p>
          <p className="text-white/70">
            Past performance — including backtested performance — does not
            guarantee future results. Trading stocks involves substantial risk
            of loss, including the loss of your entire investment.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
