-- Migration 010: Athena Thesis table
-- Stores LLM-generated narrative theses for top signals per scan run.
-- Generated by AthenaThesisService. Typically populated only for BUY_TODAY + top WATCH
-- signals to keep LLM costs bounded. Cached per (scan_run_id, ticker).
-- Run this in Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS athena_theses (
    id              BIGSERIAL PRIMARY KEY,
    scan_run_id     BIGINT REFERENCES scan_runs(id) ON DELETE SET NULL,
    stock_id        BIGINT NOT NULL REFERENCES stocks(id) ON DELETE CASCADE,
    ticker          VARCHAR(16) NOT NULL,
    verdict         VARCHAR(64) NOT NULL,
    tier            VARCHAR(64) NOT NULL,
    thesis_markdown TEXT NOT NULL,
    catalysts_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
    risks_json      JSONB NOT NULL DEFAULT '[]'::jsonb,
    trade_plan_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    input_tokens    INTEGER NOT NULL DEFAULT 0,
    output_tokens   INTEGER NOT NULL DEFAULT 0,
    model           VARCHAR(64) NOT NULL DEFAULT '',
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_athena_theses_ticker_latest
    ON athena_theses (ticker, generated_at DESC);

CREATE INDEX IF NOT EXISTS idx_athena_theses_scan_run
    ON athena_theses (scan_run_id);
